version: "1.0"
info:
  model: int-scaffold
packages:
- name: Adp22_Project
  gitServerName: shshi
  gitUrl: https://github.com/Shilpa-Shivaji-IBM
  gitUsername: Shilpa-Shivaji-IBM
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_2
  packages:
  - name: Adp22_Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_Ext
  packages:
  - name: Adp22_Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:testServce
  packages:
  - name: Adp22_Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.adp22_.integrations:flow1
  packages:
  - name: Adp22_Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.networkProtocol
  : tcp
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.password
  : "{AES}gOk3wygfWVjWqDc4SLehnQ=="
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.user
  : JDBC_BVT
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionEnabled
  : "false"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.otherProperties
  : ""
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.keyStore
  : ""
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.portNumber
  : "1521"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.networkProtocol
  : ""
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.databaseName
  : ORCL
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.keyStore
  : ""
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.dbType
  : ORACLE
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionEnabled
  : "false"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.dbType
  : ORACLE
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.serverName
  : adapter-oracle-121-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.serverName
  : adapter-oracle-121-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.trustStore
  : ""
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.otherProperties
  : driverType=thin;
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.user
  : JDBC_BVT
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionSettings.portNumber
  : "1521"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.password
  : "{AES}gOk3wygfWVjWqDc4SLehnQ=="
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Ext.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.databaseName
  : ORCL
  ? artConnection.Adp22_Project.project.adp22_.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.trustStore
  : ""
